bug fix: array with non-writable length
ngx-translate/core pull request #1371
Opened 2022-05-13 09:19 UTC by bahador-r

When I use the setTranslation method in my project, I get the following error: 

ERROR Error: Uncaught (in promise): TypeError: can't define array index property past the end of an array with non-writable length
addLangs/<@http://localhost:4200/vendor.js:145411:20
addLangs@http://localhost:4200/vendor.js:145409:11

2022-05-13 09:38 UTC, soheilrghb approved these changes
This code does not logically change the project and prevents the error.

2023-10-05 13:58 UTC, logicchemie requested changes
array with non-writable length

2024-07-16 19:38 UTC, bellaabdelouahab approved these changes

2024-11-03 12:21 UTC, CodeAndWeb commented
That change looks good for me.

However, how are you able to make this.langs (or this._langs) read-only from outside?

2024-11-03 12:45 UTC, CodeAndWeb commented
https://github.com/ngx-translate/core/commit/0818cec3107ea9bba24d9bf941201fd537380d98

2024-11-03 12:45 UTC, closed without merging